### ISSUE TITLE
PM bug

### ISSUE THREAD

**Issue by StaRTkek** [MilkywayPwns/plutoadmin#1]
![applicationframehost_2017-11-14_19-32-38](https://user-images.githubusercontent.com/33666551/32795017-2e2d66f4-c973-11e7-9fdf-89727ab22849.png)
![applicationframehost_2017-11-14_19-32-16](https://user-images.githubusercontent.com/33666551/32795028-368677dc-c973-11e7-912a-392c8814f9e7.png)
;)

**Comment by RektInator** [comment]
Fixed in the latest commit.
