### ISSUE TITLE
Give command bug

### ISSUE THREAD

**Issue by StaRTkek** [MilkywayPwns/plutoadmin#3]
![plutonium_iw5mp_2017-11-14_20-20-15](https://user-images.githubusercontent.com/33666551/32797090-578fcbbc-c979-11e7-9caf-b1e1aad6817e.jpg)
Removes alias and rank and generally doesnt work.
First i though it was a problem with the script so i edited it like this
![code_2017-11-14_20-18-59](https://user-images.githubusercontent.com/33666551/32797157-7fea9fec-c979-11e7-9d43-f29174ae7825.png)
but then i realized the rank and alias were gone

**Comment by StaRTkek** [comment]
does the same with !dvar so i guess its not a bug then

**Comment by luffynando** [comment]
@StaRTkek test with iw5_acr_mp

**Comment by RektInator** [comment]
Use the internal weapon name, iw5_acr_mp to give yourself the acr. iw5_acr_mp_camo11 to give yourself an ACR with gold camo.
